---
- hosts: localhost
  gather_facts: true
  roles:
  - role: ansible-role-openvpn

  vars:
    openvpn_server_hostname: vpn.nibspe.com.br
    clients:
    - diego.ramalho
    openvpn_port: 4300
    openvpn_push:
    - route 10.10.0.0 255.255.0.0
    - route 10.0.0.0 255.255.0.0
    openvpn_client_to_client: "true"
    openvpn_revoke_these_certs:
      -
    openvpn_crl_path: /etc/openvpn/keys/ca-crl.pem