---
- hosts: localhost
  gather_facts: true
  roles:
  - {role: ansible-role-openvpn, clients: [client1, client2, client3, client4, client5], openvpn_port: 4300, openvpn_server_network: 10.10.0.0, openvpn_server_netmask: 255.255.0.0, openvpn_client_to_client: true}